image: Visual Studio 2022
version: 1.0.{build}
configuration: Release

init:
- if "%APPVEYOR_REPO_NAME%" == "JeremyAnsel/XwaWorkspaceTools" if "%APPVEYOR_REPO_BRANCH%"=="main" if not defined APPVEYOR_PULL_REQUEST_NUMBER set DEPLOY=True

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

nuget:
  disable_publish_on_pr: true

before_build:
- nuget restore XwaWorkspaceTools\XwaWorkspaceTools.sln

build:
  project: XwaWorkspaceTools\XwaWorkspaceTools.sln
  verbosity: minimal

after_build:
- XwaWorkspaceTools\build-dist.cmd

artifacts:
- path: XwaWorkspaceTools\dist
  name: XwaWorkspaceTools-$(APPVEYOR_BUILD_VERSION)
  type: zip
